version: "3.9"

services:
  api:
    build: .
    container_name: p2-api-service
    ports:
      - "8000:8000"
    depends_on:
      - ffmpeg-service

  ffmpeg-service:
    build: ./ffmpeg_folder
    container_name: p2-ffmpeg-service
    ports:
      - "9000:9000"
